### ISSUE TITLE
mapfish_print 3.30.2 not running stable

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#145]
We have upgraded our application to pyramid_oereb 2.4.8. pyramid_oereb_mfp uses the latest commit (8d9da5ab3a8d1a8469fd693e4f86c5870ee9f6dc). At the same time, we have upgraded mapfish_print - as recommended in https://github.com/openoereb/pyramid_oereb_mfp/blob/8d9da5ab3a8d1a8469fd693e4f86c5870ee9f6dc/docker-compose.yml#L8 to version 3.30.2. However, this constellation causes problems in our test environment. Everything actually works perfectly - with the exception of PDF creation. This is not running stable. On the one hand, certain complex extracts (large geometries, many PLRs) are not created at all or only very rarely (HTTP error 500) and on the other hand, a less complex call sometimes results in an HTTP error 500 if it is called several times in succession. In the application log file, we observe errors such as

`12:41:41.866 [http-nio-8080-exec-9] WARN o.m.print.servlet.BaseMapServlet - Error while processing request: java.lang.NullPointerException: Inflater has been closed`

I have attached all log messages of an erroneous request: [single_failed_request.log](https://github.com/openoereb/pyramid_oereb_mfp/files/14190635/single_failed_request.log) and here is a log of multiple successful and failed requests: [reporting_oereb2_test.zip](https://github.com/openoereb/pyramid_oereb_mfp/files/14190651/reporting_oereb2_test.zip)

Our application runs in a Kubernetes cluster. The mapfish_print pod has 1.8 CPU and 2.2 GB RAM assigned to it. The image is configured with `-Xmx512M -Dmapfish.maxContentLength=8388608`

In the production environment (pyramid_oereb 2.4.4 and mapfish_print 3.29.4) the pods run with exactly the same resources and these problems do not occur.
My question now: have other cantons also observed this behavior? I assume that at least @michmuel has observed something similar (https://github.com/openoereb/pyramid_oereb/pull/1814#issuecomment-1711359398). Does anyone know what these errors mean? Lack of resources? Other causes?

**Comment by michmuel** [comment]
It is true, we also recognized that the image 3.30 runs less stable in Openshift than the image 3.29. I performed some local tests but have not managed to reproduce the error-prone behavior. So we still run the image 3.29.

@svamaa You run the image 3.30 with restarting the container after each print. Is that correct?

**Comment by ghost** [comment]
We run the image 3.30.6 with very high resource limits (7G) in Kubernetes. We've configured the restart of the pods after 8G of RAM was used.

**Comment by michmuel** [comment]
We run the image 3.29 with 500m CPU and 1100Mi Memory and restart the pods every 2 hours.
My impression is that the image requires quite a lot of resources for its task. Is there something related to this image that might cause some unwanted behaviour in Openshift?
How could we proceed @peterschaer, @jwkaltz ?

**Comment by peterschaer** [comment]
Sorry for the late reply, I was busy with other things. Anyway: @jwkaltz is there a reason why mapfish_print suddenly needs so many more resources? And is there a recommendation on how many resources (especially RAM) mapfish_print needs? That would help us a lot.

**Comment by jwkaltz** [comment]
@peterschaer I will discuss it with the main contributors of MapFish-Print. I do note that this phenomenon does not occur in most projects using MapFish-Print, there are reports here from you and Basel-Land, it seems the other cantons do not experience this with pyramid_oereb, and we also did not notice this effect in the geoportals running MapFish-Print. We do have a report from Basel-Stadt's geoportal about a memory leak, this is however already the case in older versions of MapFish-Print.

Furthermore, please note that MapFish-Print is currently undergoing big maintenance tasks in order to update the libraries being used and to facilitate its debugging. I do hope that this will help us to clarify what is going on in your (and Basel-Land's) use case.

**Comment by jwkaltz** [comment]
@peterschaer @michmuel can you please confirm that, in your environment, you have more problems with MapFish-Print 3.30 than with 3.29, and can you provide any more details?
There is ongoing work to improve MapFish-Print in general, but if you have anything more specific we should open a new issue in https://github.com/mapfish/mapfish-print

**Comment by peterschaer** [comment]
@jwkaltz I can confirm that we have more problems with MapFish-Print 3.30 than with 3.29. At the moment I do not have more details as I have already listed in the initial post of this issue.

**Comment by lopo977** [comment]
@jwkaltz we have still problem, with the new MPF 3.30.11 configured with -Xmx2G -Dmapfish.maxContentLength=8388608

Allocated RAM has reached almost 4 GB and the we have strange behaviors:

- java.lang.NullPointerException: Inflater has been closed
- invalid specs:
- cannot open file...
... etc
Extract as the attached PDF can be generated with 3.29 w/o problem.

[CH657302880741-22.pdf](https://github.com/user-attachments/files/17144032/CH657302880741-22.pdf)

**Comment by jwkaltz** [comment]
@lopo977 can you please provide, as a file, the print specification that MapFish-Print is processing when you have errors?
This should be visible in the MapFish-Print logs.
This way, we can try to reproduce the error in a local development environment.

**Comment by lopo977** [comment]
> @lopo977 can you please provide, as a file, the print specification that MapFish-Print is processing when you have errors? This should be visible in the MapFish-Print logs. This way, we can try to reproduce the error in a local development environment.

Here we are... this file is sometimes processed correctly in 3.30.11 and randomly MFP says that we have an error:....
[spec.json](https://github.com/user-attachments/files/17145825/spec.json)

**Comment by lopo977** [comment]
After some times something of weird happens... i.e.
[out.log](https://github.com/user-attachments/files/17145985/out.log)

in this case

`Caused by: java.lang.NullPointerException: Inflater has been closed`

```
931c3587-9cf0-49dc-a11a-f61a547446c3@0b960d38-fd27-445e-890e-d44bde71c413
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:160)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:104)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:133)
	at org.mapfish.print.servlet.job.PrintJob.lambda$call$0(PrintJob.java:150)
	at org.mapfish.print.servlet.job.PrintJob.withOpenOutputStream(PrintJob.java:120)
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:149)
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:722)
	at org.mapfish.print.processor.ProcessorDependencyGraph.tryExecuteNodes(ProcessorDependencyGraph.java:63)
	at org.mapfish.print.processor.ProcessorDependencyGraph$ProcessorGraphForkJoinTask.lambda$compute$0(ProcessorDependencyGraph.java:212)
	at org.mapfish.print.processor.AbstractProcessor$Context.mdcContext(AbstractProcessor.java:248)
	at org.mapfish.print.processor.ProcessorDependencyGraph$ProcessorGraphForkJoinTask.compute(ProcessorDependencyGraph.java:208)
	at org.mapfish.print.processor.ProcessorDependencyGraph$ProcessorGraphForkJoinTask.compute(ProcessorDependencyGraph.java:185)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.base/java.util.zip.Inflater.ensureOpen(Inflater.java:740)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:377)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:64)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpResponse.<init>(HttpRequestFetcher.java:96)
	at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpResponse.<init>(HttpRequestFetcher.java:81)
	at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.lambda$call$0(HttpRequestFetcher.java:212)
	at org.mapfish.print.processor.AbstractProcessor$Context.mdcContextEx(AbstractProcessor.java:269)
	at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.call(HttpRequestFetcher.java:204)
	at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.call(HttpRequestFetcher.java:138)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	... 5 common frames omitted
```

**Comment by michmuel** [comment]
@jwkaltz 

I tested MPF 3.30.11 in OpenShift by repeatedly calling the pdf for the same real estate. After some successful requests MFP runs into a time-out. I did not observe this behavior with MFP 3.29.

[log-27-Sep-2024-edited.txt](https://github.com/user-attachments/files/17162295/log-27-Sep-2024-edited.txt)

**Comment by lopo977** [comment]
> @jwkaltz
> 
> I tested MPF 3.30.11 in OpenShift by repeatedly calling the pdf for the same real estate. After some successful requests MFP runs into a time-out. I did not observe this behavior with MFP 3.29.
> 
> [log-27-Sep-2024-edited.txt](https://github.com/user-attachments/files/17162295/log-27-Sep-2024-edited.txt)

The anomalous behaviors of MFP happen, as time passes and the allocated memory always grows. At some point, I think, when it can't allocate more memory, the strange behaviors start.
Not related to a specific egrid. With particularly complex funds maybe you get to a critical memory allocation in less time.
The anomalies are the same reported by the other authors in this post(issue). I suspect a memory leak.

**Comment by michmuel** [comment]
@jwkaltz Are new information available concerning the image 3.30.11? Are there known issues? Does it run stably at Swisstopo?

**Comment by jwkaltz** [comment]
@lopo977 @michmuel can you please retest with the latest release, v3.31.1 ?

[UPDATE] please wait when testing. When I test it locally, I get an error, I am checking with the developers.

**Comment by lopo977** [comment]
@jwkaltz We are waiting for your signal.

**Comment by jwkaltz** [comment]
@lopo977 @michmuel the version v3.31.1 is broken, but this morning it was fixed in a new release v3.31.2, I have tested it locally with the development data of pyramid_oereb and the PDF generation via MapFish-Print is working with this release.
Can you please test this release in your environment? Please note that this release includes significant enhancements in metrics gathering and in healthcheck status visibilty. Notably, you can include this healthcheck reporting in your Kubernetes supervision if you like.
This data is available at (of course, you may need to adapt the localhost:8680 part depending on your setup):
http://localhost:8680/metrics/metrics
http://localhost:8680/metrics/healthcheck

**Comment by lopo977** [comment]
Running MPF v3.31.2
Our system is experiencing slower response times and a high number of timeouts.

[UPDATE] It seems there was an issue with the Geodienste WMS. I have now set the version to test.

**Comment by lopo977** [comment]
Running MPF v3.31.2 appears to be unstable. 
After less than 6h, it doesn't work anymore... with the following error

```
16:29:23.996 [ForkJoinPool-1-worker-251] INFO  o.m.p.processor.ProcessorGraphNode - Time taken to run processor: 'class org.mapfish.print.processor.map.AddStaticLayersProcessor' was 0 ms
16:29:23.997 [ForkJoinPool-1-worker-251] INFO  o.m.p.processor.ProcessorGraphNode - Time taken to run processor: 'class org.mapfish.print.processor.map.AddStaticLayersProcessor' was 0 ms
16:29:23.997 [ForkJoinPool-1-worker-251] INFO  o.m.p.processor.ProcessorGraphNode - Time taken to run processor: 'class org.mapfish.print.processor.map.SetStyleProcessor' was 0 ms
16:29:23.997 [ForkJoinPool-1-worker-251] INFO  o.m.p.processor.ProcessorGraphNode - Time taken to run processor: 'class org.mapfish.print.processor.map.SetFeaturesProcessor' was 0 ms
16:29:24.003 [ForkJoinPool-1-worker-251] INFO  o.m.print.map.image.wms.WmsLayer - Query the WMS image https://geodienste.ch/db/av_situationsplan_oereb_0/deu?TRANSPARENT=true&FORMAT=image%2Fpng&STYLES=&WIDTH=1740&HEIGHT=988&LAYERS=daten&REQUEST=GetMap&SRS=EPSG%3A2056&BBOX=2721674.0670634615%2C1116438.5887307692%2C2721948.2869365388%2C1116594.3322692309&VERSION=1.1.1&SERVICE=WMS.
16:29:24.616 [http-nio-8080-exec-1] WARN  o.m.print.servlet.BaseMapServlet - Error while processing request: task canceled (timeout)
16:29:27.164 [http-nio-8080-exec-1] INFO  o.m.p.s.j.impl.ThreadPoolJobManager - Submitted print job 6a10e91f-6034-4eb3-9267-f0066234dae3@2b8a841d-bd06-4408-a1cf-4f206a81ae14
```

**Comment by sebr72** [comment]
@lopo977 In 3.31.x There was quite a lot of changes in the manner the logs are written. In your example, the Logger level is INFO and WARN, not ERROR. The warning you mentionned is about something that went wrong, but not an error that's stops MFP to run as usual. Amongst 3.31.x changes: MFP is no longer hiding exceptions and the root cause of problems. Hence the number of logs is not relevant. Could you clarify what you meant by more unstable ? 
It would also help a lot if you shared the output of the metrics and healthcheck endpoints mentioned by @jwkaltz .

**Comment by lopo977** [comment]
@sebr72 @jwkaltz 
Running MPF v3.31.2
...The status after some time (not so much)..
CPU load near 0 
MEM 1.46 GB
NET load near 0

Request/response cycles:
https://cloud.geo.ti.ch/oereb2/extract/pdf/?EGRID=CH568802070726
504 Gateway Time-out
The server didn't respond in time. 

https://cloud.geo.ti.ch/oereb2/extract/pdf/?EGRID=CH540702893564
504 Gateway Time-out
The server didn't respond in time.
 
https://cloud.geo.ti.ch/oereb2/extract/pdf/?EGRID=CH769002071095
504 Gateway Time-out
The server didn't respond in time. 

[metrics]
[metrics.json](https://github.com/user-attachments/files/17644963/metrics.json)

[healthcheck.json](https://github.com/user-attachments/files/17644947/healthcheck.json)

[log]
[mfp.log](https://github.com/user-attachments/files/17644969/mfp.log)

I cannot put this version in production.
Version 3.29 works very well. 

I have to revert the production system to the mfp 3.29.
I am sorry. I produced all feedback I have in this moment.

It seems that **jobs are queued** (looking at healthcheck.json)
"WIP: Number of print jobs queued is above threshold: 4. Number of print jobs waiting is 13"

Could you help us please?

Regards.

**Comment by lopo977** [comment]
Good afternoon

Mr Riollet. @sebr72 

As agreed, I will send the mfp code and 3 spec files that you can paste into the form http://localhost:8680/

if you then push the “create and get print” button a few times, on 3 different tabs, with the 3 specs in 3 forms, after a few times the program stalls.

To start mfp type:
$ make serve

Thank you for supporting us.
[attachments.zip](https://github.com/user-attachments/files/17810695/attachments.zip)


Regards,
Luca

**Comment by lopo977** [comment]
Hi Mr. Riollet. (@sebr72)

Do you have some news about this issue?
Regard,
Luca

**Comment by sebr72** [comment]
Hi @lopo977,
Still looking. We are not in the bottom of it. But in the meantime, we noticed that the spec2.json triggers the following error: Server returned HTTP response code: 500 for URL: https://map.geo.ti.ch/oereb2/image/symbol/ch.Nutzungsplanung/legend_entry.png?identifier=423441325078
Maybe this is a part of the issue. Although it should not block afterwards the way it does

**Comment by sebr72** [comment]
Hi @lopo977 
At the same time we have spec3.json triggering the following error:
Server returned HTTP response code: 500 for URL: https://map.geo.ti.ch/oereb2/image/symbol/ch.Nutzungsplanung/legend_entry.png?identifier=527779523684
In both cases the data is not available, hence if this is working with version 3.29, I am not sure it was the correct behavior.

**Comment by lopo977** [comment]
I will check the data, even if I agree with you,  It should not block afterwards the way it does.

**Comment by lopo977** [comment]
[spec720.json](https://github.com/user-attachments/files/18110630/spec720.json)
[spec778.json](https://github.com/user-attachments/files/18110632/spec778.json)
[spec283.json](https://github.com/user-attachments/files/18110633/spec283.json)

spec files change over time and identifiers are no longer valid. Here are 3 working ones, made today.

**Comment by sebr72** [comment]
@lopo977 Indeed MFP should not block. And we found a strange behaviour in the Apache lib which stops replying after 5 failing requests. We are going to fix it.

**Comment by lopo977** [comment]
Thank you @sebr72. you did a great job.

**Comment by ybolognini** [comment]
Hello @lopo977  ,
We did some work on this issue this week. The new release 3.31.5 should solve the problem. Could you test it?

**Comment by michmuel** [comment]
> Hello @lopo977 , We did some work on this issue this week. The new release 3.31.5 should solve the problem. Could you test it?

I started to test the new image. I will provide a feedback soon.

**Comment by lopo977** [comment]
Hello. I have just started the image 3.31.5. 
Thanks for the work done.

I will provide some feedback too.

**Comment by michmuel** [comment]
Hi @ybolognini

The image 3.31.5 seems to be more stable. I did not encounter an error (hang-up) in our dev environment.

However, there still seems to be a memory issue. I provide the container 1100Mi of memory in the OpenShift cluster. Memory usage increases fast during the processing of the first few pdfs. Then, the memory increase diminishes but anyhow the container crashes after a while due to an out-of-memory error (forced by OpenShift).

I set following env vars:
PRINT_YAML_MAX_ALIASES="200"
LOG_LEVEL="DEBUG"
CATALINA_OPTS="-Xmx512M -DfileCleanUpInterval=900 -DfileCleanUpMaxAgeReport=900"

Can you indicate a variable set that prevents the memory problem? We would appreciate not having to attribute too much memory for a single print container.

Today, we restart image `camptocamp/mapfish_print:3.29.4` every 2h as otherwise the container would crash.

**Comment by sebr72** [comment]
Hi @lopo977 , @michmuel 

Could you please retest without -Xmx512 option ?

This option no longer make sense in 3,31. x and above. More importantly it was incorrect for your application (which generates large documents of 20 pages with maps)
FYI: Java always allocates the max RAM it is given, so it is not a surprising behavior that you are observing.

In a second phase I will recommend some new options (once I have done some tests on our side). But they only provide a cleaner behavior in the event of a crash, which is not what we are targeting.

**Comment by lopo977** [comment]
Hi @sebr72,
I am restarting the test w/o -Xmx512 option.
I will run the test for some hours/one day.

**Comment by lopo977** [comment]
![image](https://github.com/user-attachments/assets/c4ad786d-e7c9-4001-a0d1-d4340aaf3d86)
after 20h - no hang-up - increasing allocate mem

**Comment by svamaa** [comment]
Hey everyone
I've run tests yesterday with the image 3.31.5 in Kubernetes with 2 pods. It performed almost 2.000 prints, which startet at 9:00 and went up to 6pm.
This is the Memory usage over time. The memory remains rather constant during the test but also did not release much memory after my tests at 6pm. But suddently at 2:20 it starts releasing memory. In the logs, I get the error 
org.postgresql.util.PSQLException: ERROR: could not obtain lock on row in relation "print_job_statuses"
However I will have to run further tests to see whats happening. Seems like the DB crashed somehow.

![2025-01-10 08_06_43-Kubernetes Resources - GM - Dashboards - Grafana](https://github.com/user-attachments/assets/7eff9986-5ecb-463e-8cfa-5c5d93e841e6)

**Comment by michmuel** [comment]
I made a test without the "-Xmx512" option.  The memory behavior is similar as reported by @svamaa: It increases to approximately 1.1 GB and remains more or less stable over time. However, after 174 pdf documents the container was restarted by OpenShift due to an out-of-memory error.

**Comment by svamaa** [comment]
I have rerun the tests today. It shows the same behaviour as yesterday. I performed now more than 3000 extracts without errors or crashing. We are not running into outOfMemory Errors.
Only the used memory is never released afterwards.

**Comment by lopo977** [comment]
After 2 day
![image](https://github.com/user-attachments/assets/8bb5ce5f-84c4-4325-afc4-6f362c31b4ab)

**Comment by lopo977** [comment]
![image](https://github.com/user-attachments/assets/753bd9a0-7727-4828-87ac-ca67fed96735)
test without the "-Xmx512" option.
Memory behavior is similar as reported by @svamaa and @michmuel 
The used memory increases and never released.

**Comment by lopo977** [comment]
![image](https://github.com/user-attachments/assets/6bdde4a2-606a-4812-8ad5-053ab13c4928)
after ~ a week

**Comment by sebr72** [comment]
@lopo977 @svamaa @michmuel 
I mentioned 3 weeks ago that I was going to provide you with some more options to setup. In the meantime the master branch was updated to Java 17 which will have new options and memory impacts.
So I am planning to get back to you once I have upgraded the dependencies and created the new version of MFP.

**Comment by svamaa** [comment]
Hi @sebr72 
are there any news on this issue?

**Comment by sebr72** [comment]
@svamaa (and @lopo977 @michmuel )
During this time, we have been looking at the cost of upgrading MFP to Spring 6, our goal was to wait for this upgrade before we make a new release (including both java 17 and Spring 6). It turns out to be a very complicated and time consuming upgrade. So it won't be possible to complete the Spring upgrade without proper development.
 In the meantime, on our side we monitored our MFP servers since the fix we released to you last year and we no longer see a memory leak. So my questions are:
1) Could you please confirm if the issue is now resolved ? (one important thing to point out: Java is a technology that reserve the memory given to it, so you need JMX to monitor how much memory is effectively used by the server.)
2) Have you been running the version with the fix in production ? If not what is stopping you ?
3) Would you consider upgrading to java 17, or have you already ran the docker container from the master branch ?

**Comment by lopo977** [comment]
We are running version 3.31.5 in production. It appears to be more stable. We have allocated a significant amount of memory, and it doesn’t seem to run out of memory (OOM). If the container does go OOM, the orchestrator will automatically restart it.

**Comment by michmuel** [comment]
Hi @sebr72 

I made the tests with camptocamp/mapfish_print:3.31.5 and 500m of CPU and 1100Mi of memory. The container runs stable in OpenShift (I did not encounter any freezing) but runs into an out of memory error after some time.

For production we could use this image and continue to schedule periodic restarts as we do it with the image 3.29 now. Actually, I was hoping to be able to get rid of this procedure.

You promised to provide the optimal parameters for running the image.

**Comment by sebr72** [comment]
Hi @michmuel,

I also identified a small memory leak in 3.31. And I am in the process of fixing it in the master branch.
At the same time, I haven't forgotten about the parameters to run the image but 3.31 is in Java 11, which is already obsolete since it won't work with Spring 6. So it is pointless to waste time to optimize it.
Could you please create a separate issue for this ? (as I would like to keep [this issue](https://github.com/openoereb/pyramid_oereb_mfp/issues/145) to the points it mentioned originally).

**Comment by michmuel** [comment]
Hi @sebr72 

I am not sure if I understand you correctly. Will you provide a new image 3.31.X after fixing the memory leak? Or is it already a version 3.32.X? Are parameters still an issue for an image 3.31.X or 3.32.X?

**Comment by sebr72** [comment]
@michmuel 
At the top right of this page there is a button "New Issue". Please click on it and create a new issue with as many details as possible, or create one [here](https://github.com/mapfish/mapfish-print/issues) as there is a bug report template which helps you know the information we need.

Discussing unrelated problems in the same issue is not something I wish to do. I will make it my priority to answer all your questions there.

During the development of 3.31.x we found out that the Apache Http library did not reply more than 5 times if the http code was 500. Amongst the other changes, a lot of resources were released and memory leaks fixed, but we are regularly upgrading the libraries so new bugs might be introduced. So we would all benefit from not maintaining old versions with EOL libraries. But it also makes no sense to release 3.32 if you have identified an issue that can be fixed before Spring 6 migration.

I know of several MFP servers running 3.31.5 without the issue 145 discussed here. It makes sense to close it as soon as @svamaa and @peterschaer confirmed it.

**Comment by svamaa** [comment]
We have deployed version 3.31.5 on production today. We will monitor and test it further. I will get back to you soon.

**Comment by svamaa** [comment]
After 4 days of testing, I can say, that the version runs much more stable and releases memory every now and then. However, I cannot see a pattern within the memory graph.
It even runs stable since thursday without the scheduled restarts.

**Comment by peterschaer** [comment]
Hello everyone

As version 3.31.5 has been running without any problems for a few days now and is therefore at least as stable as 3.29.4, I am taking the liberty of closing this ticket. Any discussions about useful parameters can be continued in #149. Many thanks to everyone who has contributed to this improvement.

Peter
