### ISSUE TITLE
http-firewall error with MapFish Print 3.21 and 3.22

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb_mfp#55]
Reported by @thomasmarti in Aargau:
The print does not work if MapFish Print is upgraded from 3.20 to 3.21 or 3.22, the following error occurs:
(note that this error does not occur in local tests, so we do not know yet in which types of configurations exactly the error occurs)

15:01:40.890 [localhost-startStop-1] ERROR o.a.c.c.C.[Catalina].[localhost].[/] - Exception sending context initialized event to listener instance of class [org.mapfish.print.metrics.MapfishPrintInstrumentedFilterContextListener]

org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 15 in XML document from class path resource [mapfish-spring-security.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 40; cvc-complex-type.2.4.c: Übereinstimmungsplatzhalter ist streng, aber es kann keine Deklaration für Element 'http-firewall' gefunden werden.
         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:405)
         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:337)
         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:305)
         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
         at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
         at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
         at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
         at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135)
         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1869)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: Übereinstimmungsplatzhalter ist streng, aber es kann keine Deklaration für Element 'http-firewall' gefunden werden.
         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
         at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
         at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
         at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1912)
         at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:761)
         at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
         at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
         at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
         at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
         at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77)
         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:435)
         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:393)
         ... 26 common frames omitted

**Comment by jwkaltz** [comment]
Possibly related to Spring framework update in MapFish Print:
-    ext.springVersion = "5.1.7.RELEASE"
+    ext.springVersion = "5.2.1.RELEASE"

**Comment by jwkaltz** [comment]
Probable cause: https://github.com/mapfish/mapfish-print/issues/1251

**Comment by danduk82** [comment]
fixed by https://github.com/mapfish/mapfish-print/pull/1309
